import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";

export const metadata = {
  title: "Terms of Service | FranchiseOS",
  description: "Read the terms and conditions governing your use of FranchiseOS.",
};

export default function TermsOfServicePage() {
  return (
    <>
      <Navbar />
      <main className="flex flex-1 flex-col pt-[72px]">
        <div className="mx-auto max-w-4xl px-5 py-16 sm:px-8">
          <h1 className="text-4xl font-bold tracking-tight text-ink">
            Terms of Service
          </h1>
          <p className="mt-4 text-lg text-muted">
            Effective Date: [Effective Date]
          </p>

          <div className="prose prose-sm mt-12 max-w-none space-y-8 text-muted">
            <section>
              <h2 className="text-2xl font-semibold text-ink">1. Acceptance of Terms</h2>
              <p>
                By accessing or using FranchiseOS, Inc. ("Company", "we", "our", "us") and our software platform at [Website URL], you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you must not access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">2. Eligibility</h2>
              <p>
                You must be at least 18 years of age and capable of forming a binding contract to use our Service. By registering, you represent and warrant that you meet these eligibility requirements and have the authority to bind the business entity you represent.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">3. User Accounts</h2>
              <p>
                To access the Service, you must register for an account. You agree to provide accurate, current, and complete information and keep it updated. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use or security breach.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">4. Acceptable Use and Prohibited Activities</h2>
              <p>
                You agree not to use the Service in any way that violates applicable laws or regulations. Prohibited activities include, but are not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Engaging in illegal, fraudulent, or harmful activities.</li>
                <li>Uploading viruses, malware, or destructive code.</li>
                <li>Attempting to gain unauthorized access to our systems or bypassing security protocols.</li>
                <li>Using automated scraping, crawling, or data extraction methods without our explicit consent.</li>
                <li>Infringing on intellectual property rights.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">5. Intellectual Property</h2>
              <p>
                All rights, title, and interest in the Service, including its core software, design, text, graphics, and underlying AI architecture, remain the exclusive property of FranchiseOS, Inc. You are granted a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">6. User-Generated Content and AI-Generated Content Ownership</h2>
              <p>
                <strong>User Content:</strong> You retain ownership of any raw data, configurations, or documents you upload to the platform. By uploading, you grant us a worldwide, royalty-free license to host and process that data to provide the Service to you.
              </p>
              <p>
                <strong>AI-Generated Content:</strong> Any reports, forecasts, text, or insights generated by our AI tools based on your data are owned by you. You are free to use, distribute, and commercialize this AI-generated content for your business purposes. However, the underlying AI models and algorithms remain our property.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">7. Subscription and Billing</h2>
              <p>
                Access to the Service requires a paid subscription. You agree to pay all applicable fees associated with your selected subscription plan. All payments are processed securely via third-party payment gateways. We reserve the right to modify subscription pricing with prior notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">8. Refund Policy</h2>
              <p>
                Our standard refund policy dictates that subscriptions are generally non-refundable. However, we may offer trial periods or situational refunds under specific exceptional circumstances. Please refer to our dedicated <a href="/refund-policy" className="text-rausch hover:underline">Refund Policy</a> page for complete details.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">9. Account Suspension and Termination</h2>
              <p>
                We may suspend or terminate your account immediately, without prior notice, if you breach any of these Terms. Upon termination, your right to use the Service will cease immediately, and your data may be scheduled for deletion according to our Data Retention Policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">10. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, FranchiseOS, Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your access to or inability to access the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">11. Indemnification</h2>
              <p>
                You agree to defend, indemnify, and hold harmless FranchiseOS, Inc., its officers, directors, employees, and agents from any claims, damages, obligations, losses, liabilities, costs, or debt arising from your use of the Service or your violation of these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">12. Governing Law and Dispute Resolution</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions. Any disputes arising out of these Terms shall be resolved exclusively through binding arbitration in [Your Jurisdiction].
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">13. Changes to the Terms</h2>
              <p>
                We reserve the right to modify or replace these Terms at any time. We will notify you of any material changes via email or an in-app notification. Your continued use of the Service after any revisions become effective constitutes your acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ink">14. Contact Us</h2>
              <p>If you have any questions about these Terms, please contact us at:</p>
              <p className="mt-2">
                <strong>Email:</strong> [Contact Email]<br />
                <strong>Address:</strong> [Business Address]
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
